# Project: HeartAnimation
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -L"C:/SDL2-2.0.9/x86_64-w64-mingw32/lib" -L"C:/SDL2-2.0.9/i686-w64-mingw32/lib" -leasyx -mwindows
INCS     = -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/SDL2-2.0.9/i686-w64-mingw32/include/SDL2"
CXXINCS  = -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"C:/SDL2-2.0.9/x86_64-w64-mingw32/include/SDL2" -I"C:/SDL2-2.0.9/i686-w64-mingw32/include/SDL2"
BIN      = HeartAnimation.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
